updates compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,40 +1,41 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+# set -x          # enable debugging
 
-# parse args
-BUILD_DIR=$1
-CACHE_DIR=$2
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
+
+# clean up leaking environment
+unset GIT_DIR
+
+# Load some convenience functions like status(), echo(), and indent()
+source $bp_dir/bin/common.sh
 
 # Default Configurations -----------------------
 HTML_COMPRESSOR_OPTIONS='--recursive --simple-bool-attr --preserve-server-script --compress-css --compress-js --js-compressor closure -o'
 EXCLUDE_DIRS='\..*|_.*|bak|config|sql|fla|psd|ini|log|sh|inc|swp|dist|tmp|node_modules|bin|plugins|libs|components'
 
-source $BUILD_DIR/_webassets.cfg
+source $build_dir/_webassets.cfg
 
 EXCLUDE_DIRS="(^|/)(${EXCLUDE_DIRS})($|/)"
-
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 # Dependencies Installation --------------------
 if [[ ! $NO_GRUNT || ( ! $GRUNT_ONLY && ( ! $NO_BOWER || ( ! $NO_CSS && ( ! $NO_LESS || ! $NO_STYLUS || ! $NO_RECESS ) ) || ( ! $NO_JS && ( ! $NO_JS_IMPORTER || ! $NO_CS_IMPORT || ! $NO_REQUIREJS ) ) || ( ! $NO_HTML && ( ! $NO_JADE ) ) ) ) ]]; then
 
   # Node Installation --------------------------
-  echo "-----> Installing Node and build dependencies..."
+  status "Installing Node and build dependencies..."
   NODE_BUILDPACK_DIR=$(mktemp -d -t node.XXXXXX)
   NODE_BUILD_DIR=$(mktemp -d -t node_build.XXXXXX)
   git clone --quiet https://github.com/heroku/heroku-buildpack-nodejs.git $NODE_BUILDPACK_DIR
-  mv $LP_DIR/vendor/package-webassets.json $NODE_BUILD_DIR/package.json
+  chmod -f +x $NODE_BUILDPACK_DIR/bin/{detect,compile,release} || true
+  mv $bp_dir/vendor/package-webassets.json $NODE_BUILD_DIR/package.json
   if [[ ! $NO_GRUNT ]]; then
     (echo ","; echo -n "    \"grunt\":             \"latest\"") >> $NODE_BUILD_DIR/package.json
   fi
@@ -48,6 +49,9 @@ if [[ ! $NO_GRUNT || ( ! $GRUNT_ONLY && ( ! $NO_BOWER || ( ! $NO_CSS && ( ! $NO_
       fi
       if [[ ! $NO_STYLUS ]]; then
         (echo ","; echo -n "    \"stylus\":            \"latest\"") >> $NODE_BUILD_DIR/package.json
+      fi
+      if [[ ! $NO_BLESS ]]; then
+        (echo ","; echo -n "    \"bless\":             \"latest\"") >> $NODE_BUILD_DIR/package.json
       fi
       if [[ ! $NO_RECESS ]]; then
         (echo ","; echo -n "    \"recess\":            \"latest\"") >> $NODE_BUILD_DIR/package.json
@@ -71,8 +75,7 @@ if [[ ! $NO_GRUNT || ( ! $GRUNT_ONLY && ( ! $NO_BOWER || ( ! $NO_CSS && ( ! $NO_
     fi
   fi
   (echo ""; echo "  }"; echo -n "}") >> $NODE_BUILD_DIR/package.json
-
-  $NODE_BUILDPACK_DIR/bin/compile $NODE_BUILD_DIR $CACHE_DIR
+  $NODE_BUILDPACK_DIR/bin/compile $NODE_BUILD_DIR $cache_dir
   echo "       done."
 
   export PATH=$NODE_BUILD_DIR/bin:$NODE_BUILD_DIR/node_modules/.bin:$PATH
@@ -80,29 +83,51 @@ if [[ ! $NO_GRUNT || ( ! $GRUNT_ONLY && ( ! $NO_BOWER || ( ! $NO_CSS && ( ! $NO_
   if [[ ! $GRUNT_ONLY ]]; then
     # Ack! Installation ----------------------------
     echo -n "-----> Installing Ack!(http://betterthangrep.com)... "
-    mv $LP_DIR/vendor/ack-standalone ~/bin/ack; export PATH=~/bin:$PATH
+    mv $bp_dir/vendor/ack-standalone ~/bin/ack; export PATH=~/bin:$PATH
     (echo "--type-set=less=.less"; echo "--type-set=stylus=.styl"; echo "--type-set=sass=.sass"; echo "--type-set=scss=.scss"; echo "--type-set=coffee=.coffee"; echo "--type-set=jade=.jade") > ~/.ackrc
     echo "done"
 
-    if [[ ! $NO_SASS ]]; then
-      # SASS & Compass Installation ----------------
-      echo "-----> Installing SASS..."
-      RUBY_BUILD_DIR=$(mktemp -d -t ruby_build.XXXXXX)
-      mkdir -p $RUBY_BUILD_DIR/.gem
-      gem install sass --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
-      export GEM_PATH=$RUBY_BUILD_DIR/.gem:$GEM_PATH
-      echo "       done."
-      if [ -f "$BUILD_DIR/config.rb" ]; then
-        echo "-----> Installing Compass..."
-        gem install compass --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
+    RUBY_BUILD_DIR=$(mktemp -d -t ruby_build.XXXXXX)
+
+    if [[ ! $NO_CSS ]]; then
+      if [[ ! $NO_SASS ]]; then
+        # SASS & Compass Installation ----------------
+        status "Installing SASS..."
+        mkdir -p $RUBY_BUILD_DIR/.gem
+        gem install sass --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
+        echo "       done."
+        if [ -f "$build_dir/config.rb" ]; then
+          status "Installing Compass..."
+          gem install compass --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
+          echo "       done."
+        fi
+        # Bourbon Installation -----------------------
+        if [[ ! $NO_BOURBON ]]; then
+          status "Installing Bourbon..."
+          gem install bourbon --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
+          echo "       done."
+        fi
+      fi
+    fi
+
+    if [[ ! $NO_HTML ]]; then
+      if [[ ! $NO_HAML ]]; then
+        status "Installing Bourbon..."
+        gem install haml --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
+        echo "       done."
+      fi
+      if [[ ! $NO_SLIM ]]; then
+        status "Installing Slim..."
+        gem install slim --no-rdoc --no-ri --install-dir $RUBY_BUILD_DIR/.gem | indent
         echo "       done."
       fi
     fi
+    export GEM_PATH=$RUBY_BUILD_DIR/.gem:$GEM_PATH
 
     if [[ ! $NO_CLOSURE_COMPILE || ! $NO_HTML_COMPRESSION  ]]; then
       # Closure Compiler Fetch -----------------
       echo -n "-----> Fetching Closure Compiler... "
-      curl --silent --location http://closure-compiler.googlecode.com/files/compiler-latest.tar.gz | tar xz -C $LP_DIR/vendor/
+      curl --silent --location http://closure-compiler.googlecode.com/files/compiler-latest.tar.gz | tar xz -C $bp_dir/vendor/
       echo "done"
     fi
   fi
@@ -117,8 +142,8 @@ if [[ ! $GRUNT_ONLY ]]; then
   fi
 
   # Bower --------------------------------------
-  if [[ ! $NO_BOWER && -f $BUILD_DIR/component.json ]]; then
-    echo "-----> Installing components using Bower..."
+  if [[ ! $NO_BOWER && -f $build_dir/component.json ]]; then
+    status "Installing components using Bower..."
     eval bower install $BOWER_OPTIONS | indent
     echo "       done."
   fi
@@ -127,19 +152,19 @@ if [[ ! $GRUNT_ONLY ]]; then
   if [[ ! $NO_CSS ]]; then
 
     # Plugins Script Run -----------------------
-    echo "-----> Compiling plugins..."
-    if [ -f "$BUILD_DIR/plugins/compile" ]; then
-      chmod +x $BUILD_DIR/plugins/compile
-      $BUILD_DIR/plugins/compile $BUILD_DIR $CACHE_DIR
+    status "Compiling plugins..."
+    if [ -f "$build_dir/plugins/compile" ]; then
+      chmod +x $build_dir/plugins/compile
+      $build_dir/plugins/compile $build_dir $cache_dir
     fi
     echo "       done."
 
     # LESS -------------------------------------
     if [[ ! $NO_LESS ]]; then
-      echo "-----> Compiling LESS..."
-      ack --less -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' lessfile
+      status "Compiling LESS..."
+      ack --less -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' lessfile
       do
-        echo -n "-----> compiling ${lessfile#*$BUILD_DIR/}... " | indent
+        echo -n "-----> compiling ${lessfile#*$build_dir/}... " | indent
         fname=${lessfile%.*}
         if [[ $NO_SASS ]]; then
           eval lessc $LESS_OPTIONS "$lessfile" > "$fname.css" | indent
@@ -151,51 +176,55 @@ if [[ ! $GRUNT_ONLY ]]; then
       echo "       done."
 
       echo -n "-----> Cleaning Less... "
-      ack --less -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | xargs -0 rm -f
+      ack --less -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | xargs -0 rm
       echo "done"
     fi\
     # Stylus -----------------------------------
     if [[ ! $NO_STYLUS ]]; then
-      echo "-----> Compiling Stylus..."
-      ack --stylus -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' stylfile
+      status "Compiling Stylus..."
+      ack --stylus -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' stylfile
       do
-        echo "        compiling ${stylfile#*$BUILD_DIR/}... " | indent
+        echo "        compiling ${stylfile#*$build_dir/}... " | indent
         eval stylus $STYLUS_OPTIONS "$stylfile" | indent | indent
         echo "        done."
       done
       echo "       done."
 
       echo -n "-----> Cleaning Stylus... "
-      ack --stylus -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | xargs -0 rm -f
+      ack --stylus -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | xargs -0 rm
       echo "done"
+    fi
+
+    if [[ ! $NO_BLESS ]]; then
+       blessc
     fi
 
     # SASS -------------------------------------
     if [[ ! $NO_SASS ]]; then
-      if [[ ! -f "$BUILD_DIR/config.rb" ]]; then
-        echo "-----> Compiling SASS..."
-        ack --sass --scss -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' sassfile
+      if [[ ! -f "$build_dir/config.rb" ]]; then
+        status "Compiling SASS..."
+        ack --sass --scss -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' sassfile
         do
-          echo -n "-----> compiling ${sassfile#*$BUILD_DIR/}... " | indent
+          echo -n "-----> compiling ${sassfile#*$build_dir/}... " | indent
           eval $RUBY_BUILD_DIR/.gem/bin/sass $SASS_OPTIONS --update "$sassfile":"$sassfile" | indent
           echo "done"
         done
         echo "       done."
       else
-        echo "-----> Compiling Compass..."
-        eval $PWD/.gem/bin/compass compile $COMPASS_OPTIONS $BUILD_DIR | indent
+        status "Compiling Compass..."
+        eval $PWD/.gem/bin/compass compile $COMPASS_OPTIONS $build_dir | indent
         echo "       done."
       fi
 
       echo -n "-----> Cleaning SASS... "
-      ack --sass --scss -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | xargs -0 rm -f
+      ack --sass --scss -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | xargs -0 rm
       echo "done"
     fi
 
     # Recess -----------------------------------
     if [[ ! $NO_RECESS ]]; then
-      echo "-----> Recessing CSS files..."
-      ack --css -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' cssfile
+      status "Recessing CSS files..."
+      ack --css -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' cssfile
       do
         fname=${cssfile%.*}
         eval recess "$cssfile" $RECESS_LINT_OPTIONS | indent
@@ -206,12 +235,12 @@ if [[ ! $GRUNT_ONLY ]]; then
 
     # CSS Minification -------------------------
     if [[ ! $NO_CSS_MIN ]]; then
-      echo "-----> Compressing CSS files..."
-      ack --css -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' cssfile
+      status "Compressing CSS files..."
+      ack --css -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' cssfile
       do
-        echo -n "-----> compressing ${cssfile#*$BUILD_DIR/}... " | indent
+        echo -n "-----> compressing ${cssfile#*$build_dir/}... " | indent
         fname=${cssfile%.*}
-        eval java -jar $LP_DIR/vendor/yuicompressor-2.4.7.jar --type css $YUICOMPRESSOR_OPTIONS -o "$fname.min.css" "$cssfile" | indent
+        eval java -jar $bp_dir/vendor/yuicompressor-2.4.7.jar --type css $YUICOMPRESSOR_OPTIONS -o "$fname.min.css" "$cssfile" | indent
         csssha1=`openssl sha1 "$fname.min.css"`
         csssha1=${csssha1#*= }
         csssha1=${csssha1:0:8}
@@ -228,40 +257,40 @@ if [[ ! $GRUNT_ONLY ]]; then
     # Coffee-Script ----------------------------
     if [[ ! $NO_COFFEE_SCRIPT ]]; then
       # Coffee-Script Import -------------------
-      if [[ -f "$BUILD_DIR/Cakefile" ]]; then
+      if [[ -f "$build_dir/Cakefile" ]]; then
         echo -n "-----> Making Coffee using Cake..."
-        curr_dir=$PWD; cd $BUILD_DIR
+        curr_dir=$PWD; cd $build_dir
         eval cake build $CAKE_OPTIONS | indent
         cd $curr_dir; unset curr_dir
         echo "done"
       elif [[ ! $NO_CS_IMPORTER ]]; then
-        echo "-----> Importing & Compiling coffee-script files..."
-        ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' csfile
+        status "Importing & Compiling coffee-script files..."
+        ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' csfile
         do
-          echo -n "-----> applying imports in ${csfile#*$BUILD_DIR/}... " | indent
+          echo -n "-----> applying imports in ${csfile#*$build_dir/}... " | indent
           eval importer $importer_sm_optn $IMPORTER_CS_OPTIONS "$csfile" "${csfile%.*}.js" | indent
           echo "done"
         done
         echo "       done."
       else
         echo -n "-----> Making Coffee... "
-        ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' csfile
+        ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' csfile
         do eval coffee $CS_OPTIONS $cs_sm_optn --compile --output "$csfile" "$csfile" | indent; done
         echo "done"
       fi
 
       # Coffee-Script Clean-up -----------------
       echo -n "-----> Cleaning coffee... "
-      ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | xargs -0 rm -f
+      ack --coffee -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | xargs -0 rm
       echo "done"
     fi
 
     # JS Import --------------------------------
     if [[ ! $NO_JS_IMPORTER ]]; then
-      echo "-----> Importing JS files..."
-      ack --js -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' jsfile
+      status "Importing JS files..."
+      ack --js -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' jsfile
       do
-        echo -n "-----> applying imports in ${jsfile#*$BUILD_DIR/}... " | indent
+        echo -n "-----> applying imports in ${jsfile#*$build_dir/}... " | indent
         eval importer $importer_sm_optn $IMPORTER_JS_OPTIONS "$jsfile" "$jsfile" | indent
         echo "done"
       done
@@ -270,23 +299,23 @@ if [[ ! $GRUNT_ONLY ]]; then
 
     # Require.js -------------------------------
     if [[ $REQUIREJS ]]; then
-      echo "-----> Running Require.js files..."
-      eval r.js -o baseUrl=$BUILD_DIR $REQUIREJS_OPTIONS
+      status "Running Require.js files..."
+      eval r.js -o baseUrl=$build_dir $REQUIREJS_OPTIONS
       echo "       done."
     fi
 
     # Closure Compilation ----------------------
     if [[ ! $NO_CLOSURE_COMPILE ]]; then
       # JS Closure compilation -----------------
-      echo "-----> Compiling JS files..."
-      ack --js -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' jsfile
+      status "Compiling JS files..."
+      ack --js -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' jsfile
       do
-        echo -n "-----> compiling ${jsfile#*$BUILD_DIR/}... " | indent
+        echo -n "-----> compiling ${jsfile#*$build_dir/}... " | indent
         fname=${jsfile%.*}
         if [[ ! $NO_SOURCE_MAP ]]; then
           cc_sm_optn="--create_source_map \"$fname.min.map\" --source_map_format=V3"
         fi
-        eval java -jar $LP_DIR/vendor/compiler.jar --js "$jsfile" --js_output_file "$fname.min.js" $cc_sm_opts $CLOSURE_COMPILE_OPTIONS | indent
+        eval java -jar $bp_dir/vendor/compiler.jar --js "$jsfile" --js_output_file "$fname.min.js" $cc_sm_opts $CLOSURE_COMPILE_OPTIONS | indent
         jssha1=`openssl sha1 "$fname.min.js"`
         jssha1=${jssha1#*= }
         jssha1=${jssha1:0:8}
@@ -301,23 +330,28 @@ if [[ ! $GRUNT_ONLY ]]; then
   if [[ ! $NO_HTML ]]; then
     # Jade -------------------------------------
     if [[ ! $NO_JADE ]]; then
-      echo "-----> Compiling Jade..."
-      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' jadefile
+      status "Compiling Jade..."
+      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' jadefile
       do eval jade $JADE_OPTIONS  "$jadefile" | indent; done
       echo "       done."
 
       echo -n "-----> Cleaning Jade... "
-      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | xargs -0 rm -f
+      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | xargs -0 rm
       echo "done"
     fi
 
-    # HTML Compression
+    # Haml -------------------------------------\
+    if [[ ! $NO_HAML ]]; then
+
+    fi
+
+    # HTML Compression -------------------------
     if [[ ! $NO_HTML_COMPRESSION ]]; then
-      echo "-----> Compressing HTML..."
-      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $BUILD_DIR | while read -d $'\0' htmlfile
+      status "Compressing HTML..."
+      ack --jade -g $EXCLUDE_DIRS --invert-file-match --print0 $build_dir | while read -d $'\0' htmlfile
       do
-        echo -n "-----> compiling ${htmlfile#*$BUILD_DIR/}... " | indent
-        eval java -jar $LP_DIR/vendor/htmlcompressor-1.5.3.jar $HTML_COMPRESSOR_OPTIONS "$htmlfile" | indent
+        echo -n "-----> compiling ${htmlfile#*$build_dir/}... " | indent
+        eval java -jar $bp_dir/vendor/htmlcompressor-1.5.3.jar $HTML_COMPRESSOR_OPTIONS "$htmlfile" | indent
         echo "done"
       done
       echo "       done."
@@ -328,7 +362,7 @@ fi
 
 # Grunt Tasks --------------------------------
 if [[ $USE_GRUNT ]]; then
-  cd $BUILD_DIR
+  cd $build_dir
   eval grunt $GRUNT_OPTIONS
 fi
 
